bert_model:
  model_name: "distilbert-base-uncased"
  num_labels: 4
  output_dir: "./bert_output"
  learning_rate: 2e-5
  weight_decay: 0.01
  max_length: 128
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  warmup_steps: 500
  logging_dir: "./bert_logs"
  early_stopping_patience: 2
  batch_size: 16
  head_dims: [256] # Optional hidden layers. If empty, only one linear layer is used.
  head_dropout: 0.1 # Dropout probability for the hidden layers in the classification head
  grid_learning_rates: [1e-5, 2e-5, 3e-5]
  grid_max_lengths: [96, 128, 160]
  grid_batch_sizes: [16, 32]
  freeze_bert: false # Whether to freeze BERT layers during training to speed up training and reduce memory usage
