# Example BERT config for OmegaConf
bert_model:
  model_name: "bert-base-uncased"
  num_labels: 4
  output_dir: "./bert_output"
  num_train_epochs: 15
  save_total_limit: 2
  learning_rate: 2e-5
  max_length: 256
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  warmup_steps: 500
  logging_dir: "./bert_logs"
  early_stopping_patience: 3
  batch_size: 32
  head_dims: [512, 256] # optional hidden layers. If empty, only one linear layer is used.
  head_dropout: 0.1 # dropout probability for the hidden layers in the classification head
  grid_learning_rates: [1e-5, 1e-4, 1e-3]
  grid_max_lengths: [128, 256, 512]
  freeze_bert: true # whether to freeze BERT layers during training to speed up training and reduce memory usage
