training:
  report_to: "none"

  # Checkpointing
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  save_strategy: "epoch"
  save_steps: 160
  save_total_limit: 3

  # Early stopping
  early_stopping_patience: 2

  # Epochs & warmup
  num_train_epochs: 8
  warmup_steps: 5
  max_grad_norm: 1.0

  # Evaluation & logging
  eval_strategy: "epoch"
  eval_steps: 16
  logging_steps: 16
  logging_first_step: true
  enable_confusion_matrix_after_training: true
